apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-latest-yml
  labels:
    test: dev
    app: nginx
    env: sbx
    issue: unknown
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-yml
  template:
    metadata:
      labels:
        app: nginx-yml
    spec:
      containers:
      - name: nginx-yml
        image: nginx:v1.0
        ports:
        - containerPort: 80
