apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-latest-yml
  labels:
    app: nginx
    purpose: test
    server: amazon.com
    server2: google.com
    server3: sales.com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-yml
  template:
    metadata:
      labels:
        app: nginx-yml
    spec:
      containers:
      - name: nginx-yml
        image: nginx:v1.0
        ports:
        - containerPort: 80
